### ISSUE TITLE
Feature Request Smooth path

### ISSUE THREAD

**Issue by webserveis** [Pfuster12/LiveChart#21]
Support Smooth path

Implementation
https://www.stkent.com/2015/07/03/building-smooth-paths-using-bezier-curves.html

**Comment by Pfuster12** [comment]
This is a great feature and sample code, thanks. I'll add it to the roadmap for v1.3.0

Maybe it can be toggled with the public method:

`drawSmoothPath()`

**Comment by Pfuster12** [comment]
Actually I just came around this PathEffect, which creates the same effect by adding to the Path paint: https://developer.android.com/reference/android/graphics/CornerPathEffect.html

I think it's a simpler and native way of doing this. 

It can also allow for configuration by specifying a corner radius amount, so the smooth path can actually be part of the LiveChartStyle object, styled through the `cornerRadius` property.

**Comment by Pfuster12** [comment]
So there is two options:

1. Toggle a smooth path on/off using Stuart Kent's `PolyBezierPathUtil` using it's optimized radius.

 **Pros:** This option enables Touch overlay to work properly as path is created by LiveChart code and so can track exact coordinates in the corners.

**Cons:** More overhead in path calculation.

2. Use Android's PathEffect `CornerPathEffect(radius: Float)` and allow to change the radius in the `LiveChartStyle` object with the `mainCornerRadius` and `secondCornerRadius` properties.

**Pros:** Native and simple to implement. Allows for change of radius value.

**Cons:** The path LiveChart stores does not match the path created by the Android system to give it corner radius. Unfortunately the smooth Path Android generates is not available to use as its altered on paint. 
This means that Touch overlay breaks with high radius values as the smooth corners are not taken into account with its own path.

For 1.3.0 I will keep both options as they have advantages and disadvantages.
