### ISSUE TITLE
How to add baseline like this is there any property?

### ISSUE THREAD

**Issue by rajaroni** [Pfuster12/LiveChart#29]
I want to add this type of baseline please guide me about this.
[image](https://user-images.githubusercontent.com/14906738/98342228-f0c71f80-2031-11eb-99d7-ea4883dbc6cc.png)

**Comment by Pfuster12** [comment]
Hello rajaroni, sorry for the late answer.

This is what is called the last point label/tag. You can turn on the flag to draw it by calling this method on LiveChart:

```kotlin
// Draw last point tag label
liveChart.setDataset(data)
     .drawLastPointLabel()  // <-- Turn it on here
     .drawDataset()
```

**Comment by Pfuster12** [comment]
Right now you can't add the tag label to the baseline, it would have to be a new feature.
