### ISSUE TITLE
 is it possible to display a circular indicator without clicking on the view?

### ISSUE THREAD

**Issue by MilanMalovic** [Pfuster12/LiveChart#30]
Hello, I should display a circular indicator all the time, is that possible?

**Comment by MilanMalovic** [comment]
@Pfuster12

**Comment by Pfuster12** [comment]
Sorry for the delay, I didn't get the notification!

It is not possible right now. But we can easily add a draw flag to display the touch overlay all the time?

If you can do a PR I would appreciate it, otherwise I'll add it to the roadmap and do it at some point this month.

**Comment by Pfuster12** [comment]
#33 Opened a feature issue here
