### ISSUE TITLE
Dataset points mutability

### ISSUE THREAD

**Issue by InsanusMokrassar** [Pfuster12/LiveChart#31]
Hello. I am not pretty sure that it is good idea to use `MutableList` in `Dataset`. My point is that we could use `private val points: List<DataPoint>` instead. The reason of my suggestion in fact that it is not good when everybody knows that the list inside of `Dataset` is mutable.

**Comment by Pfuster12** [comment]
Thanks for the suggestion. Let me think about it for a bit and I'll come back to you.

I can see how the library right now does not gain anything by having a mutable list. However in the future, for example, a new feature could be added where the LiveChart is notified to redraw when there is a small change in its list of DataPoints. similar to a List view.
