### ISSUE TITLE
[Feature Request] Draw flag to always display touch overlay.

### ISSUE THREAD

**Issue by Pfuster12** [Pfuster12/LiveChart#33]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Display touch overlay all the time, not just on Touch.

Use draw flag such as `displayTouchOverlay()`

**Version**
1.3.4

**Additional context**

**Comment by MilanMalovic** [comment]
thanks for the answer Pablo, it will be great if you manage to insert it this month.

**Comment by MilanMalovic** [comment]
@Pfuster12   Hey buddy, i just need information on when you will be able to push the new version? sorry for spam

**Comment by Pfuster12** [comment]
@MilanMalovic Sorry been a bit busy this last Month.

I just finished a feature for the Axis Gravity, will include this flag in it and push it tomorrow.

**Comment by MilanMalovic** [comment]
@Pfuster12  thank you very much, I really appreciate it.
