### ISSUE TITLE
Moving circular button position without touch

### ISSUE THREAD

**Issue by MilanMalovic** [Pfuster12/LiveChart#39]
**Is your feature request related to a problem? Please describe.**

@Pfuster12  Hi Pablo, thanks for new version, this is very useful and beautiful livecharts!

**Describe the solution you'd like**

If the `.drawTouchOverlayAlways()` option is turned on, is it possible that its position is not always in the middle of the chart?
I mean, is it possible to set the position of the circular button programmatically?

**Version**
1.3.5
**Additional context**

**Comment by MilanMalovic** [comment]
@Pfuster12

**Comment by Pfuster12** [comment]
Sorry for the delay, been very busy! This will be a simple fix, I'll create a 1.3.6 release

**Comment by MilanMalovic** [comment]
@Pfuster12 Thanks man!

**Comment by Pfuster12** [comment]
I've added 3 methods I think made sense for different applications:
1. Set the overlay initial position when the drawing operation occurs (Initial position set in the underlying view draw).
2. Set the overlay DataPoint position realtime after the draw op (Programmatically set the overlay).
3. Set the overlay real pixel position realtime after the draw op (Useful for animation operations with float values).

```kotlin
   /**
     * Manually set the INITIAL nearest DataPoint position of the touch overlay.
     */
    @PublicApi
    fun setInitialTouchOverlayPosition(point: DataPoint): LiveChart

    /**
     * Manually set the overlay nearest DataPoint position at any time after the drawing operation.
     * IMPORTANT this must be called AFTER drawDataset() as the pathCoordinates
     * need to be extracted.
     */
    @PublicApi
    fun setTouchOverlayPosition(point: DataPoint)

    /**
     * Manually set the overlay REAL pixel position at any time after the drawing operation.
     * This is useful for animating the touch overlay.
     * IMPORTANT this must be called AFTER drawDataset() as the pathCoordinates
     * need to be extracted.
     * The given position will be mapped onto the path created if it exists.
     */
    @PublicApi
    fun setTouchOverlayRealPosition(position: Float)
```

It's been lightly tested so there might be bug fix releases.
