### ISSUE TITLE
When lines are smooth, path can go above and below the chart area

### ISSUE THREAD

**Issue by ergunkocak** [Pfuster12/LiveChart#41]
First of all thanks for the native library 👍 

As you can see in 1, 3 and 4 in attached screenshot

![Screenshot 2021-06-10 at 16 24 59](https://user-images.githubusercontent.com/610975/121542511-7d8eed00-ca08-11eb-9d52-58151780115a.png)

Maybe defining a default and adjustable padding from top and bottom can solve this issue?

Best

**Comment by MilanMalovic** [comment]
Hey, try to add this line in your xml that hold that chart view:

android:clipChildren="false"

**Comment by ergunkocak** [comment]
Sorry i created a duplicate for https://github.com/Pfuster12/LiveChart/issues/37 
This can be closed
